import 'package:flutter/material.dart';
import 'package:islamy/home_screen/models/sura_model.dart';
import 'package:islamy/home_screen/tabs/home_tap/sura_list.dart';

// ignore: must_be_immutable
class SuraListView extends StatelessWidget {
  SuraListView({super.key});

  List<SuraModel> sura_info = [
    SuraModel(enName: "Al-Fatiha", arName: "الفاتحة", versesCount: 7),
    SuraModel(enName: "Al-Baqarah", arName: "البقرة", versesCount: 286),
    SuraModel(enName: "Aal-E-Imran", arName: "آل عمران", versesCount: 200),
    SuraModel(enName: "An-Nisa", arName: "النساء", versesCount: 176),
    SuraModel(enName: "Al-Ma'idah", arName: "المائدة", versesCount: 120),
    SuraModel(enName: "Al-An'am", arName: "الأنعام", versesCount: 165),
    SuraModel(enName: "Al-A'raf", arName: "الأعراف", versesCount: 206),
    SuraModel(enName: "Al-Anfal", arName: "الأنفال", versesCount: 75),
    SuraModel(enName: "At-Tawbah", arName: "التوبة", versesCount: 129),
    SuraModel(enName: "Yunus", arName: "يونس", versesCount: 109),
    SuraModel(enName: "Hud", arName: "هود", versesCount: 123),
    SuraModel(enName: "Yusuf", arName: "يوسف", versesCount: 111),
    SuraModel(enName: "Ar-Ra'd", arName: "الرعد", versesCount: 43),
    SuraModel(enName: "Ibrahim", arName: "إبراهيم", versesCount: 52),
    SuraModel(enName: "Al-Hijr", arName: "الحجر", versesCount: 99),
    SuraModel(enName: "An-Nahl", arName: "النحل", versesCount: 128),
    SuraModel(enName: "Al-Isra", arName: "الإسراء", versesCount: 111),
    SuraModel(enName: "Al-Kahf", arName: "الكهف", versesCount: 110),
    SuraModel(enName: "Maryam", arName: "مريم", versesCount: 98),
    SuraModel(enName: "Ta-Ha", arName: "طه", versesCount: 135),
    SuraModel(enName: "Al-Anbiya", arName: "الأنبياء", versesCount: 112),
    SuraModel(enName: "Al-Hajj", arName: "الحج", versesCount: 78),
    SuraModel(enName: "Al-Mu'minun", arName: "المؤمنون", versesCount: 118),
    SuraModel(enName: "An-Nur", arName: "النور", versesCount: 64),
    SuraModel(enName: "Al-Furqan", arName: "الفرقان", versesCount: 77),
    SuraModel(enName: "Ash-Shu'ara", arName: "الشعراء", versesCount: 227),
    SuraModel(enName: "An-Naml", arName: "النمل", versesCount: 93),
    SuraModel(enName: "Al-Qasas", arName: "القصص", versesCount: 88),
    SuraModel(enName: "Al-Ankabut", arName: "العنكبوت", versesCount: 69),
    SuraModel(enName: "Ar-Rum", arName: "الروم", versesCount: 60),
    SuraModel(enName: "Luqman", arName: "لقمان", versesCount: 34),
    SuraModel(enName: "As-Sajda", arName: "السجدة", versesCount: 30),
    SuraModel(enName: "Al-Ahzab", arName: "الأحزاب", versesCount: 73),
    SuraModel(enName: "Saba", arName: "سبأ", versesCount: 54),
    SuraModel(enName: "Fatir", arName: "فاطر", versesCount: 45),
    SuraModel(enName: "Ya-Sin", arName: "يس", versesCount: 83),
    SuraModel(enName: "As-Saffat", arName: "الصافات", versesCount: 182),
    SuraModel(enName: "Sad", arName: "ص", versesCount: 88),
    SuraModel(enName: "Az-Zumar", arName: "الزمر", versesCount: 75),
    SuraModel(enName: "Ghafir", arName: "غافر", versesCount: 85),
    SuraModel(enName: "Fussilat", arName: "فصلت", versesCount: 54),
    SuraModel(enName: "Ash-Shura", arName: "الشورى", versesCount: 53),
    SuraModel(enName: "Az-Zukhruf", arName: "الزخرف", versesCount: 89),
    SuraModel(enName: "Ad-Dukhan", arName: "الدخان", versesCount: 59),
    SuraModel(enName: "Al-Jathiya", arName: "الجاثية", versesCount: 37),
    SuraModel(enName: "Al-Ahqaf", arName: "الأحقاف", versesCount: 35),
    SuraModel(enName: "Muhammad", arName: "محمد", versesCount: 38),
    SuraModel(enName: "Al-Fath", arName: "الفتح", versesCount: 29),
    SuraModel(enName: "Al-Hujurat", arName: "الحجرات", versesCount: 18),
    SuraModel(enName: "Qaf", arName: "ق", versesCount: 45),
    SuraModel(enName: "Adh-Dhariyat", arName: "الذاريات", versesCount: 60),
    SuraModel(enName: "At-Tur", arName: "الطور", versesCount: 49),
    SuraModel(enName: "An-Najm", arName: "النجم", versesCount: 62),
    SuraModel(enName: "Al-Qamar", arName: "القمر", versesCount: 55),
    SuraModel(enName: "Ar-Rahman", arName: "الرحمن", versesCount: 78),
    SuraModel(enName: "Al-Waqi'a", arName: "الواقعة", versesCount: 96),
    SuraModel(enName: "Al-Hadid", arName: "الحديد", versesCount: 29),
    SuraModel(enName: "Al-Mujadila", arName: "المجادلة", versesCount: 22),
    SuraModel(enName: "Al-Hashr", arName: "الحشر", versesCount: 24),
    SuraModel(enName: "Al-Mumtahina", arName: "الممتحنة", versesCount: 13),
    SuraModel(enName: "As-Saff", arName: "الصف", versesCount: 14),
    SuraModel(enName: "Al-Jumua", arName: "الجمعة", versesCount: 11),
    SuraModel(enName: "Al-Munafiqun", arName: "المنافقون", versesCount: 11),
    SuraModel(enName: "At-Taghabun", arName: "التغابن", versesCount: 18),
    SuraModel(enName: "At-Talaq", arName: "الطلاق", versesCount: 12),
    SuraModel(enName: "At-Tahrim", arName: "التحريم", versesCount: 12),
    SuraModel(enName: "Al-Mulk", arName: "الملك", versesCount: 30),
    SuraModel(enName: "Al-Qalam", arName: "القلم", versesCount: 52),
    SuraModel(enName: "Al-Haqqa", arName: "الحاقة", versesCount: 52),
    SuraModel(enName: "Al-Ma'arij", arName: "المعارج", versesCount: 44),
    SuraModel(enName: "Nuh", arName: "نوح", versesCount: 28),
    SuraModel(enName: "Al-Jinn", arName: "الجن", versesCount: 28),
    SuraModel(enName: "Al-Muzzammil", arName: "المزمل", versesCount: 20),
    SuraModel(enName: "Al-Muddaththir", arName: "المدثر", versesCount: 56),
    SuraModel(enName: "Al-Qiyama", arName: "القيامة", versesCount: 40),
    SuraModel(enName: "Al-Insan", arName: "الإنسان", versesCount: 31),
    SuraModel(enName: "Al-Mursalat", arName: "المرسلات", versesCount: 50),
    SuraModel(enName: "An-Naba", arName: "النبأ", versesCount: 40),
    SuraModel(enName: "An-Nazi'at", arName: "النازعات", versesCount: 46),
    SuraModel(enName: "Abasa", arName: "عبس", versesCount: 42),
    SuraModel(enName: "At-Takwir", arName: "التكوير", versesCount: 29),
    SuraModel(enName: "Al-Infitar", arName: "الانفطار", versesCount: 19),
    SuraModel(enName: "Al-Mutaffifin", arName: "المطففين", versesCount: 36),
    SuraModel(enName: "Al-Inshiqaq", arName: "الانشقاق", versesCount: 25),
    SuraModel(enName: "Al-Buruj", arName: "البروج", versesCount: 22),
    SuraModel(enName: "At-Tariq", arName: "الطارق", versesCount: 17),
    SuraModel(enName: "Al-A'la", arName: "الأعلى", versesCount: 19),
    SuraModel(enName: "Al-Ghashiya", arName: "الغاشية", versesCount: 26),
    SuraModel(enName: "Al-Fajr", arName: "الفجر", versesCount: 30),
    SuraModel(enName: "Al-Balad", arName: "البلد", versesCount: 20),
    SuraModel(enName: "Ash-Shams", arName: "الشمس", versesCount: 15),
    SuraModel(enName: "Al-Lail", arName: "الليل", versesCount: 21),
    SuraModel(enName: "Ad-Duhaa", arName: "الضحى", versesCount: 11),
    SuraModel(enName: "Ash-Sharh", arName: "الشرح", versesCount: 8),
    SuraModel(enName: "At-Tin", arName: "التين", versesCount: 8),
    SuraModel(enName: "Al-Alaq", arName: "العلق", versesCount: 19),
    SuraModel(enName: "Al-Qadr", arName: "القدر", versesCount: 5),
    SuraModel(enName: "Al-Bayyina", arName: "البينة", versesCount: 8),
    SuraModel(enName: "Az-Zalzala", arName: "الزلزلة", versesCount: 8),
    SuraModel(enName: "Al-Adiyat", arName: "العاديات", versesCount: 11),
    SuraModel(enName: "Al-Qari'a", arName: "القارعة", versesCount: 11),
    SuraModel(enName: "At-Takathur", arName: "التكاثر", versesCount: 8),
    SuraModel(enName: "Al-Asr", arName: "العصر", versesCount: 3),
    SuraModel(enName: "Al-Humaza", arName: "الهمزة", versesCount: 9),
    SuraModel(enName: "Al-Fil", arName: "الفيل", versesCount: 5),
    SuraModel(enName: "Quraish", arName: "قريش", versesCount: 4),
    SuraModel(enName: "Al-Ma'un", arName: "الماعون", versesCount: 7),
    SuraModel(enName: "Al-Kawthar", arName: "الكوثر", versesCount: 3),
    SuraModel(enName: "Al-Kafirun", arName: "الكافرون", versesCount: 6),
    SuraModel(enName: "An-Nasr", arName: "النصر", versesCount: 3),
    SuraModel(enName: "Al-Masad", arName: "المسد", versesCount: 5),
    SuraModel(enName: "Al-Ikhlas", arName: "الإخلاص", versesCount: 4),
    SuraModel(enName: "Al-Falaq", arName: "الفلق", versesCount: 5),
    SuraModel(enName: "An-Nas", arName: "الناس", versesCount: 6)
  ];

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text("Suras List",
            style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w700,
                color: Colors.white)),
        ListView.separated(
            physics: NeverScrollableScrollPhysics(),
            shrinkWrap: true,
            scrollDirection: Axis.vertical,
            itemCount: sura_info.length,
            itemBuilder: (context, index) => SuraList(
                  sura_info: sura_info[index],
                  index: index,
                ),
            separatorBuilder: (BuildContext context, int index) => Divider(
                  color: Colors.white,
                  endIndent: MediaQuery.of(context).size.width * 0.15,
                  indent: MediaQuery.of(context).size.width * 0.15,
                ))
      ],
    );
  }
}
